language: python
python:
  - '2.7'
before_install:
- sudo apt-get install -y curl tar
- bash install-apex.sh
- eval export AWS_ACCESS_KEY_ID=\$${TRAVIS_BRANCH}_aws_access_key_id
- eval export AWS_SECRET_ACCESS_KEY=\$${TRAVIS_BRANCH}_aws_secret_access_key
- eval export AWS_REGION=\$${TRAVIS_BRANCH}_aws_region
install:
- bash install-requirements.sh
- pip install coveralls
script: coverage run setup.py test
after_success:
- coveralls
deploy:
- provider: script
  skip_cleanup: true
  script: ./apex deploy --env master && ./register_module.sh https://api.door43.org/tx/module
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: ./apex deploy && ./register_module.sh https://test-api.door43.org/tx/module
  on:
    branch: develop

